### ISSUE TITLE
没有数据库,方便提供下数据库sql吗

### ISSUE THREAD

**Issue by 1971341230** [baiwumm/Vue3-Admin#3]

**Comment by yonghuili1** [comment]
+1

**Comment by baiwumm** [comment]
兄弟们，醒目点呀，想要 sql 的点个 star，留下邮箱，看到会发

**Comment by yonghuili1** [comment]
> 兄弟们，醒目点呀，想要 sql 的点个 star，留下邮箱，看到会发

1437891764@qq.com   😊thanks

**Comment by baiwumm** [comment]
> > 兄弟们，醒目点呀，想要 sql 的点个 star，留下邮箱，看到会发
> 
> [1437891764@qq.com](mailto:1437891764@qq.com) 😊thanks

点个 star 呀，白嫖都舍不得动动手吗，看到 star 后会发

**Comment by saiigo** [comment]
> 兄弟们，醒目点呀，想要 sql 的点个 star，留下邮箱，看到会发

已star，sai_igo@126.com，tks

**Comment by niehuijie** [comment]
704503898@qq.com 😊thanks

**Comment by LHoul** [comment]
1470733845@qq.com😊thanks

**Comment by unityKai** [comment]
787431259@qq.com 😊thanks

**Comment by hj-cherrytrees** [comment]
516652620@qq.com   😊thanks

**Comment by blue-blue** [comment]
@baiwumm 已star，946245813@qq.com，😊thanks
