### ISSUE TITLE
貌似没有数据库，能发下吗？谢谢

### ISSUE THREAD

**Issue by LHoul** [baiwumm/Vue3-Admin#4]
1470733845@qq.com  ，已star

**Comment by baiwumm** [comment]
> [1470733845@qq.com](mailto:1470733845@qq.com) ，已star

链接:https://pan.baidu.com/s/1fFassbJNDH03ZJ5cP68wgw?pwd=bxme 提取码:bxme 复制这段内容后打开百度网盘手机App，操作更方便哦
